FROM node:7.9.0-slim

RUN apt-get update && apt-get install -y curl apt-transport-https \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update \
  && apt-get install -y yarn \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# COPY package.json package.json
# COPY yarn.lock yarn.lock
# RUN yarn install && yarn cache clean

# COPY . .
